/**:
  ros__parameters:
    ntrip:
      host: "212.156.70.42"
      user_name: "K0734204801"
      password: "JyjWVP"
      mount_point: "VRSRTCM31"
      port: 2101
      use_nav_sat_fix_init: true
      nav_sat_fix_topic_name: "clap/ros/gps_nav_sat_fix"
      init_ntrip_location_lat: 0.0000000000
      init_ntrip_location_lon: 0.0000000000

    serial_port:
      publish_port_rtcm: true
      name: "/dev/ttyUSB0"
      baud_rate: 115200

    rtcm_publisher:
      publish_rtcm: true
      rtcm_topic: "rtcm"
      rtcm_frame_id: "rtcm"
